# Generated by Django 5.1.1 on 2024-09-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='speak_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('messege', models.TextField(max_length=250)),
            ],
        ),
    ]
