# Generated by Django 5.1.1 on 2024-09-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0003_alter_speak_me_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='speak_me',
            table='speak_me',
        ),
    ]
