# Generated by Django 5.1.1 on 2024-09-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0005_alter_speak_me_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speak_me',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
