# Generated by Django 5.1.1 on 2024-09-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0006_alter_speak_me_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='speak_me',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
